Added interaction listeners to GuiInventory
minevn/minevn-library pull request #11
Opened 2024-06-14 00:33 UTC by SinonCute

2024-06-15 13:07 UTC, amadeusmz requested changes

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +        actions = new GuiItemStack[inv.getSize()];
Trước anh nhớ là api ver cũ class `Inventory` không có hàm `getSize`, có gì em tìm link javadoc của minecraft 1.8 rồi dẫn link xác nhận giúp anh nha  
(mà để tiết kiệm thời gian research những điểm như này, tốt nhất nên hạn chế refactor nếu không cần thiết)

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> -    public void openIventory(Player viewer) {
không thay đổi cấu trúc của class, vì nó sẽ ảnh hưởng đến các nơi gọi  
tương tự hàm `onClose` (line 97-)

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiListener.java
> +        boolean top = false, bottom = false;
- Tương tự: Chỗ này anh cũng không chắc là nếu holder bị null thì sẽ như thế nào  
  Để giảm tải cho người review, em hãy dẫn link tài liệu cụ thể nêu rằng chỗ này không cần check null  
  (nếu nó đang ổn thì không nên sửa)
- Để đỡ xấu hơn thì hãy viết `if (holder instanceof GuiInventory == false)`
- Điều kiện if có một statement cũng phải đưa vào scope `{}`
- Bỏ bớt những hàng trống
- Sửa tên 2 biến `top` & `bottom` thành `isTopClick` & `isBottomClick`

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +        return viewer != null && viewer.getOpenInventory().getTopInventory().getHolder() == this && viewer.isOnline();
Sẽ có trường hợp `viewer != null` nhưng `viewer.isOnline() = false`. Anh đã từng bị.  
Nguyên tắc là cái gì có thể xảy ra thì mình phải cover hết.

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiListener.java
> -        if (inv == null) {
Vì các api phiên bản cũ anh nhớ là không có annotation `@NotNull`, nên chỗ này vẫn cần check null kể cả IDE có báo warning

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiListener.java
> +        if (e.getSlotType() == InventoryType.SlotType.OUTSIDE) return;
thêm vào scope `{}`

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +    private boolean manualHandle = false;
Sửa tên biến và hàm setter của biến này thành `isDraggingAllowed`

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +    private Consumer<InventoryCloseEvent> onClose;
Sửa tên các biến này thành: `topClickAction`, `bottomClickAction`, ...

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +        }
sửa đoạn này thành `setItem(slot, null)`

2024-06-15 13:07 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +    public void setOnClose(Consumer<InventoryCloseEvent> onClose) { this.onClose = onClose; }
bổ sung giúp anh video test cho các implementation mà em đã thêm nha  
(nguyên tắc là self-check trước khi request review)

2024-06-18 13:44 UTC, SinonCute commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +        actions = new GuiItemStack[inv.getSize()];
https://helpch.at/docs/1.8.8/index.html?org/bukkit/inventory/Inventory.html

Có nha anh.

2024-06-18 13:58 UTC, SinonCute commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +        return viewer != null && viewer.getOpenInventory().getTopInventory().getHolder() == this && viewer.isOnline();
em chỉ đảo vị trí, để em fix lại.

2024-06-18 13:58 UTC, SinonCute commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiListener.java
> +        boolean top = false, bottom = false;
Em đã sửa tên biến, xóa hàng trống, và thêm check null cho holder.

2024-06-18 14:03 UTC, SinonCute commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +    private Consumer<InventoryCloseEvent> onClose;
yes sir

2024-06-18 14:03 UTC, SinonCute commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +    private boolean manualHandle = false;
yes sir

2024-06-18 14:04 UTC, SinonCute commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +        }
yes sir

2024-06-18 14:59 UTC, SinonCute commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +    public void setOnClose(Consumer<InventoryCloseEvent> onClose) { this.onClose = onClose; }
https://discord-cdn-proxy.karyl.workers.dev/?https://cdn.discordapp.com/attachments/1102133845341507594/1252630045332078592/Jdk-17_2024.06.18_-_07.23.25.02.mp4

2024-07-21 10:45 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +    public void setCloseAction(Consumer<InventoryCloseEvent> closeAction) { this.closeAction = closeAction; }
Đoạn này viết inline hơi khó đọc, em xuống dòng giúp anh nha

2024-07-21 10:45 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiListener.java
> +        if (e.getSlotType() == InventoryType.SlotType.OUTSIDE) return;
thêm vào scope và xuống hàng nha

2024-07-21 11:01 UTC, amadeusmz requested changes
@SinonCute   
Fix giúp anh một số điểm nha nữa

2024-07-21 11:01 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiInventory.java
> +
Mình không khuyến khích viết inline như này, em sửa lại xuống dòng giúp anh nha

2024-07-21 11:01 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiListener.java
> +        if (e.getSlotType() == InventoryType.SlotType.OUTSIDE) return;
Mình xuống hàng bên trong scope nha em

```java
if (e.getSlotType() == InventoryType.SlotType.OUTSIDE) {
    return;
}
```

2024-07-21 11:01 UTC, amadeusmz commented on minevnlib-bukkit/src/main/java/net/minevn/guiapi/GuiListener.java
> +        boolean top = false, bottom = false;
Các scope `{}` em xuống hàng nha.

Những điểm khác đã ổn.

2024-07-26 17:21 UTC, amadeusmz approved these changes
Các case đã test:
- [x] API hiện có: Chạy ổn với DotMan
- [ ] API được bổ sung trong PR (test bởi người code)

2024-07-26 17:21 UTC, merged