Thêm GitHub Actions cho MineVNLib
minevn/minevn-library pull request #2
Opened 2024-02-28 14:21 UTC by minhh2792

Khi có push lên branch `master`, action sẽ khởi chạy với cấu hình từ `./github/workflows/build.yml`. Các bước bao gồm build MineVNLib, sau đó tạo pre-release với version là commit sha trigger action đó (rút gọn)

Demo 1 action mẫu kèm artifact: https://github.com/minhh2792/minevn-library/actions/runs/8081809122

## Test case:
- [x] Build ML
- [x] Tạo pre-release

2024-02-28 14:40 UTC, amadeusmz commented
Trong release chỉ có source code, không có file jar?

https://github.com/minhh2792/minevn-library/releases/tag/8bcb194

2024-02-28 15:18 UTC, minhh2792 commented
> Trong release chỉ có source code, không có file jar?
> 
> https://github.com/minhh2792/minevn-library/releases/tag/8bcb194

tag đó em viết lỗi, anh xem tag mới nhất nhé
https://github.com/minhh2792/minevn-library/releases

2024-02-28 15:38 UTC, amadeusmz commented on .github/workflows/build.yml
> +      - name: Build ML
sửa lại không ghi tắt MineVNLib giúp anh nha

2024-02-28 15:41 UTC, minhh2792 commented on .github/workflows/build.yml
> +      - name: Build ML
đã sửa

2024-02-28 15:44 UTC, amadeusmz commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.hash }}
nên thêm version name vào tag, theo format `version-commithash`. ví dụ: `1.0.0-abcde00`

commit hash lấy từ `build.gradle.kts`. anh không rõ là gradle có task nào print ra version name không?

2024-02-28 15:54 UTC, minhh2792 commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.hash }}
`echo "::set-output name=version::$(awk '/version =/ {gsub("\"", "", $NF); print $NF}' build.gradle.kts | sed 's/[[:space:]]//g')"`

2024-02-28 16:00 UTC, minhh2792 commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.hash }}
đã bổ sung
output:
![image](https://github.com/minevn/minevn-library/assets/63439671/9cf9b131-83a5-45a5-8975-e9a9ea95f799)

2024-02-28 16:11 UTC, amadeusmz commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.hash }}
nên viết task mới trong build.gradle.kts để print ra version, không nên cắt như này

2024-02-29 01:03 UTC, minhh2792 commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.hash }}
Print ra mình vẫn phải cắt thôi chứ không có cách truyền vào step

2024-02-29 01:05 UTC, minhh2792 commented
Tạm tắt draft để cho action chạy thử

2024-02-29 13:45 UTC, amadeusmz commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.hash }}
nhưng mà sẽ đỡ ugly hơn cách này

viết thêm task trong `build.gradle.kts` giúp anh nha

2024-03-01 04:30 UTC, amadeusmz commented on build.gradle.kts
> +
chỗ này nên đưa vào trong scope `tasks` luôn

```kotlin
tasks {
  get("printVersion") {
    doLast ...
  }
  
  ...
}
```

2024-03-01 06:18 UTC, amadeusmz commented on .github/workflows/build.yml
> +          title: "MineVNLib - ${{ steps.git.outputs.hash }}"
Ở đây cũng thêm version luôn

2024-03-01 06:19 UTC, amadeusmz commented on .github/workflows/build.yml
> +          echo "::set-output name=version::$(./gradlew :minevnlib-plugin:printVersion | awk 'NR==2')"
cái này có thể gom chung với task `name: Get commit sha` không? ví anh thấy có thể trả ra nhiều output

2024-03-01 16:39 UTC, minhh2792 commented on build.gradle.kts
> +
Em đã đưa vào scop

2024-03-01 16:39 UTC, minhh2792 commented on .github/workflows/build.yml
> +          title: "MineVNLib - ${{ steps.git.outputs.hash }}"
E đã thêm version vào title

2024-03-01 16:41 UTC, minhh2792 commented on .github/workflows/build.yml
> +          echo "::set-output name=version::$(./gradlew :minevnlib-plugin:printVersion | awk 'NR==2')"
Em gom vào task Build MineVNLib rồi, lý do là project phải được build thì task printVersion mới hoạt động

2024-03-02 08:45 UTC, amadeusmz requested changes

2024-03-02 08:45 UTC, amadeusmz commented on build.gradle.kts
> +import org.gradle.api.tasks.TaskAction
import không sử dụng

2024-03-02 08:45 UTC, amadeusmz commented on .github/workflows/build.yml
> +          echo "::set-output name=version::$(./gradlew :minevnlib-plugin:printVersion | awk 'NR==2')"
nếu vậy thì có thể đưa get commit sha vào task build luôn được không em

2024-03-02 15:57 UTC, minhh2792 commented on build.gradle.kts
> +import org.gradle.api.tasks.TaskAction
em đã xoá unused

2024-03-03 07:04 UTC, amadeusmz approved these changes

2024-03-03 07:04 UTC, merged